---
- name: Check DH params exist
  file:
    dest: /etc/nginx/dhparams.pem
    state: file
  register: has_dhparams
  ignore_errors: yes

- name: Create new DH params
  shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
  notify: reload nginx
  when: has_dhparams|failed
