---
- name: Install nginx
  yum: name=nginx enablerepo=epel

- name: Create sites.d
  file: dest=/etc/nginx/uwsgi-sites.d state=directory

- name: Drop default config
  file: dest=/etc/nginx/conf.d/default.conf state=absent
  notify: reload nginx
  tags: default_server

- name: Create include
  copy: dest=/etc/nginx/conf.d/00-uwsgi.conf content="include /etc/nginx/uwsgi-sites.d/*.conf;"
  notify: reload nginx

- name: Create master cofnig
  template: dest=/etc/nginx/nginx.conf src=nginx.conf.j2
  notify: reload nginx

- name: Enable nginx
  service: name=nginx enabled=yes state=running

- name: Enable ports 80 & 443
  firewalld: permanent=yes immediate=yes
             service={{ item }} zone=public state=enabled
  with_items: [ http, https ]
  ignore_errors: yes